require("@nomicfoundation/hardhat-toolbox");
require("dotenv").config();

// https://hardhat.org/hardhat-runner/docs/advanced/create-task
// task("balance", "Prints an account's balance")
//   .addParam("account", "The account's address")
//   .setAction(async (taskArgs) => {
//     const balance = await ethers.provider.getBalance(taskArgs.account);

//     console.log(ethers.utils.formatEther(balance), "ETH");
//   });

//Task to print out a bunch of test accounts generated by hardhat
task("accounts", "Print the list of accounts").setAction(
  async (taskArg, hre) => {
    const accounts = await hre.ethers.getSigners();

    for (const account of accounts) {
      console.log(account.address);
    }
  }
);

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.17",
  networks: {
    goerli: {
      url: process.env.STAGING_QUICKNODE_KEY,
      accounts: [process.env.PRIVATE_KEY],
    },
  },
};
